---
title: "Interim Deliverable II"
author: "Ye Chen, Jen Lee, Runjie Lu and Danielle Simms"
date: "11/16/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
*pData is the dataset we handled the missing data, pcData is the original dataset
```{r data, include=FALSE}
pData = read.csv("PilgrimCaseData.csv")
pcData = read.csv("PilgrimCaseData.csv")
```

```{r handleMissingData, echo=FALSE}
eliminateNull <- function(x) { 
  meanX = mean(x,na.rm = TRUE)
  for (i in 1:length(x)){
    if (is.na(x[i])) {
      #print(i)
      x[i] = meanX
    }
  }
  return(x)
}

getmode <- function(v) {
  uniqv <- unique(v)
  uniqv[which.max(tabulate(match(v, uniqv)))]
}

eliminateNullFactor <- function(x) { 
  modeX = getmode(x[!is.na(x)])
  print(modeX)
  for (i in 1:length(x)){
    if (is.na(x[i])) {
      #print(i)
      x[i] = modeX
    }
  }
  return(x)
}


pData$X9Profit = eliminateNull(pcData$X9Profit)
pData$X9Age = eliminateNullFactor(pcData$X9Age)
pData$X9Inc = eliminateNullFactor(pcData$X9Inc)
pData$X9Tenure = eliminateNull(pcData$X9Tenure)
pData$X0Profit = eliminateNull(pcData$X0Profit)
pData$X9District = eliminateNullFactor(pcData$X9District)
```

```{r Question3MissingData}
pcData = read.csv("PilgrimCaseData.csv")

listProfit = pcData$X9Profit
mean(listProfit)

#Create a new matrix with age, income and profit
listAge_Profit <- matrix(c(pcData$X9Age,pcData$X9Inc,pcData$X9Profit), ncol = 3)

#Create another matrix without the missing data(eliminate those rows which have missing data)
listAge_Profit_NoNA = listAge_Profit[!is.na(listAge_Profit[,1]),]
listAge_Profit_NoNA = listAge_Profit_NoNA[!is.na(listAge_Profit_NoNA[,2]),]
listAge_Profit_NoNA = listAge_Profit_NoNA[!is.na(listAge_Profit_NoNA[,1]),]

View(listAge_Profit_NoNA)
length(listAge_Profit_NoNA)
mean_WNA = mean(listAge_Profit[,3])

mean_NoNA = mean(listAge_Profit_NoNA[,3])
sd_NONA = sd(listAge_Profit_NoNA[,3])
size_NoNA = length(listAge_Profit_NoNA) / 3
var_NoNA = var(listAge_Profit_NoNA[,3])

#t test whether missing data effect the result
t.test(listAge_Profit[,3],listAge_Profit_NoNA[,3],paired = FALSE)

#t test whether handling missing data with mode affect the result
t.test(listAge_Profit[,3],pData$X9Profit,paired = FALSE)

#Before 1999
median(listAge_Profit_NoNA[,3])
#After 1999
median(pData$X9Profit)

#Before 2000
median(pcData$X0Profit,na.rm = TRUE)
#After 2000
median(pData$X0Profit)
```

```{r t-testForQuestion5}
pData_withOnline9 = pData[pData$X9Online==1,]
pData_withoutOnline9 = pData[pData$X9Online==0,]
t.test(pData_withOnline9$X9Profit,pData_withoutOnline9$X9Profit,paired = FALSE)
pData_withOnline0 = pData[pData$X0Online==1,]
pData_withoutOnline0 = pData[pData$X0Online==0,]
t.test(pData_withOnline0$X0Profit,pData_withoutOnline0$X0Profit,paired = FALSE)

pData_withEbilling9 = pData[pData$X9Billpay == 1,]
pData_withoutEbilling9 = pData[pData$X9Billpay == 0,]
t.test(pData_withEbilling9$X9Profit,pData_withoutEbilling9$X9Profit,paired = FALSE)
pData_withEbilling0 = pData[pData$X0Billpay == 1,]
pData_withoutEbilling0 = pData[pData$X0Billpay == 0,]
t.test(pData_withEbilling0$X0Profit,pData_withoutEbilling0$X0Profit,paired = FALSE)
```

```{r retentionCreate}
getRetention <- function(x,y) {
  z = c(1:length(x))
  for (i in 1: length(x)) {
    if (!is.na(x[i]) && !is.na(y[i])) {
      if (x[i] == 1 && y[i] == 1) {
        z[i] = 1
      } else {
        z[i] = 0
      }
    } else {
      z[i] = NA
    }
  }
  return (z)
}

pData$Retention = getRetention(pcData$X9Online,pcData$X0Online)
```

